### ISSUE TITLE
Term highlighting and custom excerpts

### ISSUE THREAD

**Issue by rickertl** [FacetWP/facetwp-relevanssi#2]
Just like SearchWP, Relevannsi has the ability to highlight search terms and have custom excerpts. I saw some customizations at https://gist.github.com/jchristopher/184c5e8748b92a6db751 for SearchWP to get this to work. It would be awesome for this to happen for the Relevanssi integration as well.

**Comment by rickertl** [comment]
Not sure if this will help, but per this link below, query_posts() and WP_Query() cause problems. I don't have that in my Display Code section, but maybe you do in the plugin core.

http://www.relevanssi.com/knowledge-base/query_posts/

Thanks.

**Comment by mgibbs189** [comment]
I think he's referring to a `query_posts()` or `WP_Query` instance on the default search page, that is in effect overriding the default search.

**Comment by rickertl** [comment]
Hi there. Just wondering if there is any update on fixing this issue? Thanks.
