### ISSUE TITLE
Modifying Code to Work with Relevanssi Premium

### ISSUE THREAD

**Issue by lizrobcodes** [FacetWP/facetwp-relevanssi#3]
Hello @mgibbs189

I was wondering if you could point me in the right direction or tell me what changes I need to make in your code for this integration plugin to work with Relevanssi Premium. I am working on a site for a client, and she purchased the premium version -- I didnt think of it after that this integration was for the free version. Any information you have will be helpful. I do have the premium plugin, but took it down since this is public. If you need the plugin to look at the code, I can send to you. Or if you know what you need to look at, just let me know I can send the file you need. Thank you so much, I really appreciate any and all help on this.

**Comment by mgibbs189** [comment]
Hey @lizrobcodes sorry for the delay -- there shouldn't be any changes needed between Relevanssi and Relevanssi Premium. Is it not working for you?
